<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6PxveUG\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6PxveUG/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6PxveUG.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6PxveUG\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6PxveUG\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6PxveUG',
    'container.build_id' => '9b277ad9',
    'container.build_time' => 1649200520,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6PxveUG');
